### PR TITLE
Version change to 0.2.0

### PR DESCRIPTION
**Pull request by benjaminbollen**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/sentinel/31)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @inetic

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by Viv-Rajkumar** [comment]
@benjaminbollen  what happened to v 0.1 :)

---

Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/sentinel/31)

**Comment by benjaminbollen** [comment]
I see your point; :)

**Pull request closed without merging**
