### PR TITLE
renames Sentinel to PureSentinel

### PR DESCRIPTION
**Pull request by mmoadeli**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/sentinel/39)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @benjaminbollen

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by inetic** [comment]
Hi @mmoadeli, is this WIP?

**Comment by mmoadeli** [comment]
@inetic I do not see any further PureSentinel in sentinel library.  Not in documentations and not in code.
So, as far as task description is concerned I do not take it as a WIP.

**Pull request merged**
